import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider"



const inter = Inter({subsets: ["latin"], variable: "--font-inter"});
const jetbrains = JetBrains_Mono({subsets: ["latin"], variable: "--font-mono"});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className={`${inter.variable} ${jetbrains.variable} overscroll-none h-full antialiased`}>
      <body className=" min-h-full overscroll-none flex flex-col">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
